#!/usr/bin/env python3
"""
Build a per-ticker "abnormal" list from recent DailyReplay results.

This is used by the weekend batch incremental policy:
- "regular" tickers can reuse last week's best params
- "abnormal" tickers are force re-optimized (full search)

Input
-----
Reads recent `analysis/daily_trades_YYYYMMDD.csv` (no suffix) generated by:
  `tools/simulate_daily_replay.py`

Output
------
- `data/universe/abnormal_codes_latest.csv` (default)
- optionally a dated snapshot: `data/universe/abnormal_codes_<tag>.csv`
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
from pathlib import Path
from typing import Iterable, List, Tuple

import pandas as pd

ANALYSIS_DIR = Path("analysis")
OUT_DIR = Path("data/universe")


def _parse_date_tag(path: Path) -> str | None:
    match = re.match(r"daily_trades_(\d{8})\.csv$", path.name, flags=re.IGNORECASE)
    return match.group(1) if match else None


def _iter_recent_trade_files(days: int) -> List[Tuple[str, Path]]:
    files: List[Tuple[str, Path]] = []
    for path in ANALYSIS_DIR.glob("daily_trades_*.csv"):
        tag = _parse_date_tag(path)
        if not tag:
            continue
        files.append((tag, path))
    files.sort(key=lambda item: item[0])
    if days > 0:
        files = files[-days:]
    return files


def _load_trades(paths: Iterable[Path]) -> pd.DataFrame:
    frames: List[pd.DataFrame] = []
    for path in paths:
        try:
            df = pd.read_csv(path)
        except Exception:
            continue
        if df.empty:
            continue
        frames.append(df)
    if not frames:
        return pd.DataFrame()
    return pd.concat(frames, ignore_index=True)


def _normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df
    out = df.copy()
    if "code" not in out.columns:
        for alt in ("ticker", "Ticker", "Code"):
            if alt in out.columns:
                out = out.rename(columns={alt: "code"})
                break
    if "pnl_yen" not in out.columns:
        for alt in ("pnl", "pnlJPY", "pnl_jpy"):
            if alt in out.columns:
                out = out.rename(columns={alt: "pnl_yen"})
                break
    return out


def _compute_abnormal_codes(
    trades: pd.DataFrame,
    *,
    min_trades: int,
    pf_th: float,
    winrate_th: float,
    require_pnl_nonneg: bool,
) -> pd.DataFrame:
    if trades.empty:
        return pd.DataFrame(columns=["code", "trades", "pnl_yen_sum", "pf", "winrate", "reason"])

    trades = _normalize_columns(trades)
    if "code" not in trades.columns or "pnl_yen" not in trades.columns:
        return pd.DataFrame(columns=["code", "trades", "pnl_yen_sum", "pf", "winrate", "reason"])

    pnl = pd.to_numeric(trades["pnl_yen"], errors="coerce").fillna(0.0)
    codes = trades["code"].astype(str).str.strip().str.upper()
    trades = trades.assign(code=codes, pnl_yen=pnl)

    grouped = trades.groupby("code", as_index=False)["pnl_yen"].agg(
        trades="count",
        pnl_yen_sum="sum",
        pnl_pos_sum=lambda s: float(s[s > 0].sum()),
        pnl_neg_sum=lambda s: float(s[s < 0].sum()),
        wins=lambda s: int((s > 0).sum()),
    )

    grouped["winrate"] = grouped["wins"] / grouped["trades"].clip(lower=1)
    grouped["pf"] = grouped.apply(
        lambda row: (row["pnl_pos_sum"] / abs(row["pnl_neg_sum"])) if row["pnl_neg_sum"] < 0 else 999.0,
        axis=1,
    )

    grouped = grouped[grouped["trades"] >= int(min_trades)].copy()
    if grouped.empty:
        return pd.DataFrame(columns=["code", "trades", "pnl_yen_sum", "pf", "winrate", "reason"])

    reasons: List[str] = []
    abnormal_mask = pd.Series([False] * len(grouped))

    pnl_bad = grouped["pnl_yen_sum"] < 0
    pf_bad = grouped["pf"] < float(pf_th)
    win_bad = grouped["winrate"] < float(winrate_th)

    if require_pnl_nonneg:
        abnormal_mask = pnl_bad | pf_bad | win_bad
    else:
        abnormal_mask = pf_bad | win_bad

    for _, row in grouped.iterrows():
        reason_parts: List[str] = []
        if row["pnl_yen_sum"] < 0:
            reason_parts.append("pnl<0")
        if row["pf"] < float(pf_th):
            reason_parts.append(f"pf<{pf_th:g}")
        if row["winrate"] < float(winrate_th):
            reason_parts.append(f"win<{winrate_th:g}")
        reasons.append(",".join(reason_parts) if reason_parts else "")

    grouped["reason"] = reasons
    out = grouped.loc[abnormal_mask, ["code", "trades", "pnl_yen_sum", "pf", "winrate", "reason"]].copy()
    out = out.sort_values(["pnl_yen_sum", "pf", "winrate", "code"], ascending=[True, True, True, True]).reset_index(drop=True)
    return out


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--days", type=int, default=10, help="How many recent daily_trades_YYYYMMDD.csv files to use (default 10)")
    ap.add_argument("--min-trades", type=int, default=5, help="Minimum trades per ticker in the window (default 5)")
    ap.add_argument("--pf-th", type=float, default=1.0, help="PF threshold (default 1.0)")
    ap.add_argument("--winrate-th", type=float, default=0.5, help="Winrate threshold (default 0.5)")
    ap.add_argument(
        "--require-pnl-nonneg",
        action="store_true",
        help="Also mark tickers abnormal when window pnl_yen_sum < 0 (recommended)",
    )
    ap.add_argument("--out-latest", default=str(OUT_DIR / "abnormal_codes_latest.csv"))
    ap.add_argument("--out-tag", default="", help="Optional dated snapshot output path (CSV).")
    ap.add_argument(
        "--tag",
        default=dt.date.today().strftime("%Y%m%d"),
        help="Date tag for logs/snapshot (YYYYMMDD). Default: today.",
    )
    return ap.parse_args()


def main() -> None:
    args = parse_args()
    recent = _iter_recent_trade_files(int(args.days))
    tags = [t for t, _ in recent]
    paths = [p for _, p in recent]

    trades = _load_trades(paths)
    df_ab = _compute_abnormal_codes(
        trades,
        min_trades=int(args.min_trades),
        pf_th=float(args.pf_th),
        winrate_th=float(args.winrate_th),
        require_pnl_nonneg=bool(args.require_pnl_nonneg),
    )

    out_latest = Path(args.out_latest)
    out_latest.parent.mkdir(parents=True, exist_ok=True)

    if df_ab.empty:
        pd.DataFrame({"code": []}).to_csv(out_latest, index=False, encoding="utf-8-sig")
    else:
        df_ab[["code"]].to_csv(out_latest, index=False, encoding="utf-8-sig")

    if args.out_tag:
        out_tag = Path(args.out_tag)
        out_tag.parent.mkdir(parents=True, exist_ok=True)
        if df_ab.empty:
            pd.DataFrame({"code": []}).to_csv(out_tag, index=False, encoding="utf-8-sig")
        else:
            df_ab.to_csv(out_tag, index=False, encoding="utf-8-sig")

    print(
        {
            "days_used": len(paths),
            "date_tags": tags,
            "abnormal_codes": int(len(df_ab)),
            "out_latest": str(out_latest),
            "out_tag": str(args.out_tag) if args.out_tag else "",
        }
    )


if __name__ == "__main__":
    main()
